language: node_js

node_js:
  - '8'
  - '10'
  - '11'

before_install:
# show product version
  - npm i -g npm@latest
  - nvm --version
  - node --version
  - npm --version

install:
  - npm ci
  - npm run build:dev

script:
  - npm run lint
  - npm test
